#ifndef CONFIG_H
#define CONFIG_H

#define IMAGES_DIRECTORY_PATH "images/"

#define FIELD_WIDTH_DEFAULT  10
#define FIELD_HEIGHT_DEFAULT 10

#define FIELD_IMG_WIDTH_DEFAULT  216
#define FIELD_IMG_HEIGHT_DEFAULT 217


#endif // CONFIG_H
