#ifndef CONSTANTS_H
#define CONSTANTS_H

const int FIELD_WIDTH_DEFAULT  = 10;
const int FIELD_HEIGHT_DEFAULT = 10;

const int FIELD_IMG_WIDTH_DEFAULT  = 216;
const int FIELD_IMG_HEIGHT_DEFAULT = 217;

const int MYFIELD_IMG_X = 40;
const int MYFIELD_IMG_Y = 127;

const int MYFIELD_IMG_REL_X = MYFIELD_IMG_X;
const int MYFIELD_IMG_REL_Y = 39;

const int ENEMYFIELD_IMG_X = 322;
const int ENEMYFIELD_IMG_Y = 127;

const int ENEMYFIELD_IMG_REL_X = ENEMYFIELD_IMG_X;
const int ENEMYFIELD_IMG_REL_Y = 39;

#endif // CONSTANTS_H
